export default {
  products: [
    {
      _id: '1',
      name: "Pant of Paris" , 
      category: 'Pants',
      image: '/images/longPant.jpeg',
      price: 59,
      brand: 'Hiskywin',
      countInStock: 6,
    },
    {
      _id: '2',
      name: "Pant of Belgium" , 
      category: 'Pants',
      image: '/images/longPant2.jpeg',
      price: 70,
      brand: 'Nike',
      countInStock: 6,
      
    },
    {
      _id: '3',
      name: "Pant of Berlin" ,  
      category: 'Pants',
      image: '/images/longPant3.jpeg',
      price: 59,
      brand: 'Adidas',
      countInStock: 6,
    },
    {
      _id: '4',
      name: "Pant of Zurich" , 
      category: 'Pants',
      image: '/images/shortPant.jpeg',
      price: 90,
      brand: 'Under Armour',
      countInStock: 6,
    },
    {
      _id: '5',
      name: "Pant of London" , 
      category: 'Pants',
      image: '/images/shortPant2.jpeg',
      price: 119,
      brand: 'Champion',
      countInStock: 6,
    },
    {
      _id: '6',
      name: "Pant of Jerusalem" , 
      category: 'Pants',
      image: '/images/shortPant3.jpeg',
      price: 85,
      brand: 'Aelfric Eden',
      countInStock: 6,
    },
  ],
};
